### ISSUE TITLE
EPIC: Issues related to defunct public authorities

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/alaveteli#92]
- [x] Defunct body is listed in batch request authorities list selection #6039
- [ ] Users can request email change for defunct bodies #5300
- [ ] exclude defunct public bodies from the public body statistics page #1484

Alaveteli version 0.33.0.0

**Comment by schlos** [comment]
Defunct body is listed in batch request authorities list selection mysociety#6039 is fixed with Alaveteli v0.38.3.0.
